#!/bin/bash

echo "🚀 Déploiement du système de villes favorites..."

# Instructions pour le serveur de production
echo "📋 Instructions pour le serveur de production :"
echo ""
echo "1. Connectez-vous au serveur de production"
echo "2. Allez dans le dossier du projet"
echo "3. Exécutez les commandes suivantes :"
echo ""
echo "   cd /path/to/your/project"
echo "   git pull origin main"
echo "   php artisan migrate --force"
echo "   php artisan cache:clear"
echo "   php artisan view:clear"
echo "   php artisan config:clear"
echo ""
echo "4. Vérifiez que la colonne 'is_favorite' a été ajoutée à la table 'cities' :"
echo "   php artisan tinker"
echo "   >>> \App\Models\City::first()"
echo "   >>> exit"
echo ""
echo "5. Testez les fonctionnalités :"
echo "   - Page /admin/cities avec filtres"
echo "   - Boutons favoris"
echo "   - Filtrage par région/département"
echo ""
echo "✅ Déploiement terminé !"
