#!/bin/bash

echo "🔧 Déploiement de la correction de route..."

# Instructions pour le serveur de production
echo "📋 Instructions pour le serveur de production :"
echo ""
echo "1. Connectez-vous au serveur de production"
echo "2. Allez dans le dossier du projet"
echo "3. Exécutez les commandes suivantes :"
echo ""
echo "   cd /path/to/your/project"
echo "   git pull origin main"
echo "   php artisan route:clear"
echo "   php artisan cache:clear"
echo "   php artisan view:clear"
echo "   php artisan config:clear"
echo ""
echo "4. Vérifiez que la route existe :"
echo "   php artisan route:list | grep admin.ads.index"
echo ""
echo "5. Testez les pages :"
echo "   - /admin/ads/service-cities"
echo "   - /admin/ads/keyword-cities"
echo "   - /admin/ads/manual"
echo ""
echo "✅ Déploiement terminé !"
