{{-- Style éditorial : portfolio & avis en tête, hiérarchie visuelle forte --}}
@include('home.partials.hero')
@include('home.partials.portfolio')
@include('home.partials.stats')
@include('home.partials.services')
@include('home.partials.reviews')
@include('home.partials.about')
@include('home.partials.cities')
@include('home.partials.france-departments-map')
@include('home.partials.how-it-works')
@include('home.partials.ecology-financing')
@include('home.partials.why-choose-us')
@include('home.partials.featured-partner')
@include('home.partials.partners-logos')
@include('home.partials.cta')
@include('home.partials.scripts')
