{{-- Mise en avant services & réalisations, hero plus impactant --}}
@include('home.partials.hero')
@include('home.partials.stats')
@include('home.partials.services')
@include('home.partials.portfolio')
@include('home.partials.about')
@include('home.partials.cities')
@include('home.partials.how-it-works')
@include('home.partials.ecology-financing')
@include('home.partials.reviews')
@include('home.partials.why-choose-us')
@include('home.partials.featured-partner')
@include('home.partials.partners-logos')
@include('home.partials.cta')
@include('home.partials.scripts')
